micronaut:
  application:
    name: rinha-backend-kotlin
  server:
    port: 9001
    cors:
      enabled: true

datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgresql
    url: ${DATABASE_URL}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    dialect: POSTGRES
    minPoolSize: 1
    maxPoolSize: 10
jpa:
  default:
    packages-to-scan:
      - 'io.github.luizimcpi'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: false
flyway:
  datasources:
    default:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3

jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  property-naming-strategy: SNAKE_CASE