version: '3.4'
services:

  database:
    restart: on-failure
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: "postgres"
    container_name: database
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '400MB'